services:
  oracledb:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: SuperSecretPassword
      ORACLE_USER: ADRIAN
      APP_USER: ADRIAN
      APP_USER_PASSWORD: SuperSecretPassword
    ports:
      - "1521:1521"
    volumes:
      - ./init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s ADRIAN/SuperSecretPassword@//localhost:1521/XEPDB1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  migrator:
    build:
      context: ./FootballProject.DbUp
      dockerfile: Dockerfile
    depends_on:
      oracledb:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "User Id=ADRIAN;Password=SuperSecretPassword;Data Source=//oracledb:1521/XEPDB1"

    volumes:
      - ./FootballProject.DbUp/Migrations:/app/Migrations
    entrypoint: ["dotnet", "FootballProject.DbUp.dll"]
    restart: "no"

  footballproject:
    build:
      context: ./FootballProject
      dockerfile: Dockerfile
    depends_on:
      oracledb:
        condition: service_healthy
      migrator:
        condition: service_started  # Note: Docker Compose v3 doesn't support `service_completed_successfully`
    environment:
      - ConnectionStrings__DefaultConnection=User Id=ADRIAN;Password=SuperSecretPassword;Data Source=//oracledb:1521/XEPDB1
    ports:
      - "8080:8080"

volumes:
  oracle-data:
