-- Create user EKSTRAKLASA if it does not exist
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'EKSTRAKLASA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER EKSTRAKLASA IDENTIFIED BY SuperSecretPassword';
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO EKSTRAKLASA';
        EXECUTE IMMEDIATE 'ALTER USER EKSTRAKLASA QUOTA UNLIMITED ON USERS';
    END IF;
END;
/

