CREATE TABLE IF NOT EXISTS Transfers (
     TransferID SERIAL PRIMARY KEY,
     PlayerID INTEGER REFERENCES Players(PlayerID) ON DELETE CASCADE,
    FromTeamID INTEGER REFERENCES Teams(TeamID) ON DELETE SET NULL,
    ToTeamID INTEGER REFERENCES Teams(TeamID) ON DELETE SET NULL,
    TransferDate DATE,
    TransferFee DECIMAL(15, 2)
    );